#Blue Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
        - name: bluepod
          image: devopswithcloud/nginx:blue
          ports:
            - containerPort: 80
---
#Blue service
apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  type: NodePort #We will move to cluster ip later
  selector:
    app: blue-app
  ports:
    - port: 80
      targetPort: 80
---

# orange Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orange-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orange-app
  template:
    metadata:
      labels:
        app: orange-app
    spec:
      containers:
      - image: devopswithcloudhub/nginx:orange
        name: orangepod
        ports:
        - containerPort: 80
---
# orange Service
apiVersion: v1
kind: Service
metadata:
  name: orange-service
spec:
  type: NodePort
  selector:
    app: orange-app
  ports:
  - port: 80
    targetPort: 80
---
# green Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
      - image: devopswithcloudhub/nginx:green
        name: greenpod
        ports:
        - containerPort: 80
---
# green Service
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  type: NodePort
  selector:
    app: green-app
  ports:
  - port: 80
    targetPort: 80
---
#Ingress resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: context-ingress
  annotations:
    kubernetes.io/ingress.class: "gce" #if you using nginx then change it here if you dont mention anything, 
spec:                                  #It will create in default ingress in gce
  # ingressClassName: "gce" - latest approach we can Use this instead of anotation
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:  
            name: blue-service
            port:
              number: 80    #port of the service
---
#pathType: Prefix is one of the path matching strategies in Kubernetes Ingress
#Prefix means the path matching is based on the URL starting with the specified path. It matches the beginning of the request path.
#This matches EVERY path because every URL starts with /:
#Ingress is namespace scoped
#kubectl get ingress
---
#Ingress resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: context-ingress
  annotations:
    kubernetes.io/ingress.class: "gce" 
    #gce-internal for internal loadbalancer
spec:                                 
  defaultBackend:
    service:
      name: orange-service
      port:
        number: 80  
  rules:
  - http:
    paths:
    - pathType: Prefix
      path: "/blue"
      backend:
        service:
          name: blue-service
          port: 
            number: 80
    - pathType: Prefix
      path: "/green"
      backend:
        service:
          name: green-service
          port:
            number: 80
---
# Request → Load Balancer IP
#     ↓
# Check path:
#     - If path starts with "/blue"  → Route to blue-service
#     - If path starts with "/green" → Route to green-service  
#     - Everything else → Route to orange-service (defaultBackend)
---

    
